services:
  jira-tinder:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        NODE_ENV: production
    image: jira-tinder:production
    container_name: jira-tinder-prod
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
    volumes:
      - ./logs:/app/logs
      - ./uploads:/app/uploads
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3001/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "com.jira-tinder.description=Jira Tinder Production Application"
      - "com.jira-tinder.version=1.0.0"
      - "com.jira-tinder.environment=production"
      - "com.jira-tinder.maintainer=dev-team"
    networks:
      - jira-tinder-prod-network
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'

  nginx:
    image: nginx:alpine
    container_name: jira-tinder-nginx-prod
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
      - ./logs/nginx:/var/log/nginx
    depends_on:
      - jira-tinder
    restart: unless-stopped
    networks:
      - jira-tinder-prod-network
    labels:
      - "com.jira-tinder.description=Nginx Production Reverse Proxy"
      - "com.jira-tinder.environment=production"
      - "com.jira-tinder.profile=production"
    deploy:
      resources:
        limits:
          memory: 128M
          cpus: '0.2'
        reservations:
          memory: 64M
          cpus: '0.1'

  # Optional: Redis for caching (uncomment if needed)
  # redis:
  #   image: redis:alpine
  #   container_name: jira-tinder-redis
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - redis_data:/data
  #   restart: unless-stopped
  #   networks:
  #     - jira-tinder-prod-network
  #   command: redis-server --appendonly yes

networks:
  jira-tinder-prod-network:
    driver: bridge
    name: jira-tinder-prod-network

# volumes:
#   redis_data:
#     driver: local
